export default {
  // Auth
  AUTH_REGISTER: 'auth/FETCH_REGISTER',
  AUTH_LOGIN: 'auth/FETCH_LOGIN',
  AUTH_FETCH_START: 'auth/FETCH_START',
  AUTH_FETCH_SUCCESS: 'auth/FETCH_SUCCESS',
  AUTH_FETCH_FINISH: 'auth/FETCH_FINISH',
  AUTH_FETCH_ERROR: 'auth/FETCH_ERROR',
  LOGED_TRUE: 'LOGED_TRUE',
  LOGED_FALSE: 'LOGED_FALSE',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  // Balance
  BALANCE_FETCH_SUCCESS: 'balance/FETCH_SUCCESS',
  BALANCE_FETCH_ERROR: 'balance/FETCH_ERROR',
  // Global
  GLOBAL_FETCH_START: 'global/FETCH_START',
  GLOBAL_FETCH_FINISH: 'global/FETCH_FINISH',
  GLOBAL_FETCH_ERROR: 'global/FETCH_ERROR',
  IS_MODAL_LOGOUT_OPEN: 'global/IS_MODAL_LOGOUT_OPEN',
  IS_MODAL_LOGOUT_CLOSE: 'global/IS_MODAL_LOGOUT_CLOSE',
  IS_MODAL_DELETE_OPEN: 'global/IS_MODAL_DELETE_OPEN',
  IS_MODAL_DELETE_CLOSE: 'global/IS_MODAL_DELETE_CLOSE',
  IS_MODAL_ADD_INCOME_OPEN: 'global/IS_MODAL_ADD_INCOME_OPEN',
  IS_MODAL_ADD_INCOME_CLOSE: 'global/IS_MODAL_ADD_INCOME_CLOSE',

  // Products
  PRODUCTS_FETCH_START: 'products/FETCH_START',
  PRODUCTS_FETCH_FINISH: 'products/FETCH_FINISH',
  PRODUCTS_FETCH_ERROR: 'products/FETCH_ERROR',
  PRODUCTS_FETCH_SUCCESS: 'products/FETCH_SUCCESS',
  PRODUCTS_CREATE_SUCCESS: 'products/CREATE_SUCCESS',

  // Categories
  CATEGORIES_FETCH_START: 'categories/FETCH_START',
  CATEGORIES_FETCH_FINISH: 'categories/FETCH_FINISH',
  CATEGORIES_FETCH_ERROR: 'categories/FETCH_ERROR',
  CATEGORIES_FETCH_SUCCESS: 'categories/FETCH_SUCCESS',

  // Income
  INCOME_FETCH_ERROR: 'income/FETCH_ERROR',
  INCOME_FETCH_SUCCESS: 'income/FETCH_SUCCESS',

  // Costs
  COSTS_FETCH_SUCCESS: 'costs/FETCH_SUCCESS',
  COSTS_FETCH_ERROR: 'costs/FETCH_ERROR',
  COSTS_DEL_SUCCESS: 'del_success',
  COSTS_DEL_ERROR: 'del_err',
  COSTS_DEL_RESET: 'del_res',

  // Transactions
  TRANSACTIONS_FETCH_START: 'transactions/FETCH_START',
  TRANSACTIONS_FETCH_SUCCESS: 'transactions/FETCH_SUCCESS',
  TRANSACTIONS_FETCH_ERROR: 'transactions/FETCH_ERROR',
  TRANSACTIONS_FETCH_FINISH: 'transactions/FETCH_FINISH',
  TRANSACTIONS_SET_TO_DELETE: 'transactions/SET_TO_DELETE',
  TRANSACTIONS_RESET: 'transactions/TRANSACTIONS_RESET',
};
